'use strict';mix_d("SimilaritiesUICards__p13n-desktop-sims-fbt:p13n-desktop-sims-fbt__7HNTBgCj","exports tslib @c/browser-operations @c/scoped-dom @c/error-handling @c/aui-untrusted-ajax @c/logger @p/A".split(" "),function(Y,z,ha,ia,ja,ka,la,ma){function A(a){return a&&"object"===typeof a&&"default"in a?a:{"default":a}}var Z=A(ha),f=A(ia),P=A(ja),na=A(ka),Q=A(la),oa=A(ma),pa={ctiList:["Website/Personalization/Report a Problem CX"],category:"Website",type:"Personalization",item:"Report a Problem CX",
folder:"9c9c97c9-6f69-4dba-a55d-26045c6a3068",group:"P13N Report a Problem CX"},qa=[{ctiList:["Website/Personalization/Similarities","Website/Detail Page/Similarities"],category:"Website",type:"Personalization",item:"Similarities",folder:"4d16d05d-9a17-4b36-b8fe-9ee159ff81de",group:"Similarities"}],ua=function(a){var e=f["default"].cardRoot.querySelector(".p13n-report-flag"),c=Z["default"].setup();c.define("showFlag","mouseover",function(){e.classList.remove("p13n-report-flag-hide")});c.define("hideFlag",
"mouseout",function(){e.classList.add("p13n-report-flag-hide")});c.attach("showFlag",a);c.attach("hideFlag",a);var b=f["default"].cardRoot.querySelector(".internal-flag-form"),d=b.querySelector(".internal-flag-env-data").dataset,h=b.querySelector(".internal-flag-title-text"),g=b.querySelector(".internal-flag-description").firstElementChild,p=b.querySelector(".internal-flag-alias"),w=b.querySelector(".internal-flag-response-message"),x=function(l){l.preventDefault();l=function(m){return!m||!m.trim()};
if(l(h.value)||l(g.value)||l(p.value))return R(w,!1,"Something went wrong. One of the required fields was missing."),!1;l=f["default"].cardRoot.querySelectorAll(".a-dynamic-image");var q;if(q=f["default"].cardRoot.querySelector(".a-carousel-heading")){var B=ra(a,l.length);q="Internal user reported issue '"+h.value+"' with widget: "+q.innerText}else B=sa(a),q="Internal user reported issue '"+h.value+"'";l=ta(l,B,g.value,p.value,d);var n=pa;qa.forEach(function(m){m.ctiList.includes(d.cti)&&(n=m)});
na["default"].post("https://p13ngoals.corp.amazon.com/sims",{accepts:"text/html, application/json",contentType:"application/json;charset=UTF-8"},{sim_params:{assigned_folder:n.folder,description:l,descriptionContentType:"text/amz-markdown-sim",extensions:{tt:{assignedGroup:n.group,category:n.category,impact:5,item:n.item,type:n.type}},tags:[{id:"internal-problem-generated"}],title:q}}).then(function(m){R(w,!0,m)}).catch(function(m){R(w,!1,m)});return!1};b.onsubmit=function(l){return x(l)};c=f["default"].cardRoot.querySelector(".p13n-desktop-report-problem-flag-data");
if(c.dataset.name)oa["default"].on("a:popover:hide:"+c.dataset.name,function(){b.reset();w.innerText=""})},ra=function(a,e){if(!a.dataset.aCarouselOptions)return Q["default"].log("Empty ASIN List in carouselElement.dataset.aCarouselOptions","ERROR"),[];a=JSON.parse(a.dataset.aCarouselOptions).ajax.id_list;var c=f["default"].cardRoot.querySelector(".a-carousel-firstvisibleitem");c=(Number(c.value)||1)-1;return a.map(function(b){return JSON.parse(b).id}).slice(c,c+e)},sa=function(a){return(a=a.dataset.asinList)?
a.split(","):[]},ta=function(a,e,c,b,d){for(var h="",g=0;g<a.length;g++){var p=a[g];h+=(p?"![]("+p.src+")":"IMAGE MISSING")+"\nASIN: "+(e[g]?e[g]:"ASIN MISSING")+"\n\n"}return"**This SIM-T ticket is created by the 'Report a Problem' internal tool. To know more, here's its wiki: https://w.amazon.com/bin/view/Personalization/CoreRecommendations/Projects/Canaries/Report-a-Problem-UX-on-P13NWidget/UserGuide/**\n\n**Alias:** ["+(b+"](https://phonetool.amazon.com/users/"+b+")\n**Comment:** "+c+"\n\n**Widget Group ID:** "+
d.widgetGroupId+"\n**Strategy ID:** "+d.strategyId+"\n**CTI:** "+d.cti+"\n**Facets:** ")+(d.facets+"\n**Content Reftag:** "+d.reftag+"\n"+(""!==d.baseAsin?"**Page ASIN:** "+d.baseAsin+"\n":"")+"\n**SessionID:** ")+(d.sessionId+"\n**MarketplaceID:** "+d.marketplaceId+"\n**Device Type:** "+d.deviceType+"\n\n**List of ASINs:**\n\n")+h},R=function(a,e,c){e?(a.classList.remove("a-color-error"),c.responseBody&&"object"===typeof c.responseBody?c.responseBody.response&&c.responseBody.response.id?a.innerHTML=
"Success, here's the <a href=\"https://t.corp.amazon.com/"+c.responseBody.response.id+'" target="_blank">SIM-T ticket</a> you created.':(Q["default"].log("Fail to find the id of the SIM-T ticket created in the response body of response data.","ERROR"),a.innerText="Success, but we could not find the link to the SIM-T ticket."):(Q["default"].log("The response body of response data is not an object.","ERROR"),a.innerText="Success, but we could not find the link to the SIM-T ticket.")):(a.classList.add("a-color-error"),
a.innerText="string"===typeof c?c:"Oops! Something went wrong. Please try again.")},va={setupModal:function(a){return z.__awaiter(void 0,void 0,void 0,function(){var e;return z.__generator(this,function(c){e=f["default"].cardRoot.querySelector(".p13n-report-problem-modal-root");if(!e)return[2];ua(a);return[2]})})}},wa=function(a,e){e?a.classList.add("add-to-cart-item-disabled"):a.classList.remove("add-to-cart-item-disabled");a.querySelectorAll("input").forEach(function(c){e?c.setAttribute("disabled",
"true"):c.removeAttribute("disabled")})},aa=function(a,e){a=f["default"].cardRoot.querySelector("#add-to-cart-item-"+a);if(!a)return P["default"].error('Missing Add to Cart item!", "add-to-cart.client.item-state-handler',"changeItemStatus");if(!(e&&a.classList.contains("add-to-cart-item-disabled")||!e&&!a.classList.contains("add-to-cart-item-disabled"))){wa(a,e);var c;for(a=e=0;3>a;a++){var b=f["default"].cardRoot.querySelector("#add-to-cart-item-"+a);if(!b)break;b.classList.contains("add-to-cart-item-disabled")||
e++}var d=f["default"].cardRoot.getElementsByClassName("add-to-cart-section")[0];a=d.getElementsByClassName("a-button-text")[0];b=d.getElementsByClassName("add-to-cart-button")[0];d=d.getElementsByClassName("add-to-cart-string-data")[0];if(null===(c=null===d||void 0===d?void 0:d.dataset)||void 0===c?0:c.displayStringList)var h=JSON.parse(d.dataset.displayStringList);b&&(0===e?b.classList.add("a-button-disabled"):b.classList.remove("a-button-disabled"));a?h&&h.length>e?a.innerText=h[e]:P["default"].error('Missing Add to Cart string!", "add-to-cart.client.item-state-handler',
"updateButtonString"):P["default"].error('Missing Add to Cart button!", "add-to-cart.client.item-state-handler',"updateButtonString")}},fa=function(a){return z.__awaiter(void 0,void 0,void 0,function(){var e,c,b,d,h,g,p,w,x,l,q,B,n,m,E,F,S,G,ba,L,v,H,M,T,U,V,W,ca,y,C;return z.__generator(this,function(D){if((b=f["default"].cardRoot.getElementsByClassName("cardRoot")[0])&&"true"===b.dataset.punt)return[2];d=1;b&&b.dataset.count&&(d=Number(b.dataset.count));b&&b.dataset.components&&(h=JSON.parse(b.dataset.components));
b&&b.dataset.addToCart&&(g=JSON.parse(b.dataset.addToCart));b&&b.dataset.priceTotals&&(p=JSON.parse(b.dataset.priceTotals));b&&b.dataset.pointsTotal&&(w=JSON.parse(b.dataset.pointsTotal));if(h&&p){D=h;for(var I=d,J=[],t=[],k=0;k<I;k++){var u=k+1;1<u&&(J[k]=f["default"].cardRoot.getElementsByClassName("thumbnailPlus-"+String(u))[0]);t[k]=f["default"].cardRoot.getElementsByClassName("thumbnail-"+String(u))[0]}var X=!1,da=0,ea="";for(k=0;k<I;k++){u=String(k+1);var K=J[k],N=t[k];D[u]&&D[u].checked?(aa(k,
!1),da++,ea+=u,0===k?X=!0:K&&(X?K.style.display="unset":(X=!0,K.style.display="none")),N&&(N.style.display="unset")):(aa(k,!0),K&&(K.style.display="none"),N&&(N.style.display="none"))}e=da;c=ea;D=h;I=d;J=[];for(t=0;t<I;t++)k=t+1,J[t]=f["default"].cardRoot.getElementsByClassName("asin-"+String(k))[0];for(t=0;t<I;t++)k=String(t+1),u=J[t],D[k]&&D[k].checked?u&&(u.style.opacity="100%"):u&&(u.style.opacity="50%");x=e;l=p[c];q=f["default"].cardRoot.getElementsByClassName(a.totalLabel)[0];B=f["default"].cardRoot.getElementsByClassName(a.totalAmount)[0];
n=f["default"].cardRoot.getElementsByClassName(a.addItems)[0];m=f["default"].cardRoot.getElementsByClassName(a.chooseItems)[0];E=f["default"].cardRoot.getElementsByClassName(a.actionDetails)[0];F=f["default"].cardRoot.getElementsByClassName(a.sidePanel)[0];0===x?(n&&(n.style.display="none"),q&&(q.style.display="none"),m&&(m.style.display="unset"),E&&(E.style.visibility="hidden"),F&&(F.style.display="none")):(l?(q&&B&&(B.innerText=l,q.style.display="block"),n&&(n.style.display="none"),m&&(m.style.display=
"none")):(n&&(n.style.display="inline-block"),m&&(m.style.display="none"),q&&(q.style.display="none")),E&&(E.style.visibility="visible"),F&&(F.style.display="flex"));b&&h&&w&&(S=f["default"].cardRoot.getElementsByClassName(a.pointsAmount)[0],G=f["default"].cardRoot.getElementsByClassName(a.totalPointsLabel)[0],(ba=w[c])?G&&S&&(S.innerText=ba,G.style.display="block"):G&&(G.style.display="none"));L=void 0;b&&b.dataset.optimalPrice&&(L=JSON.parse(b.dataset.optimalPrice));b&&h&&L&&(v=f["default"].cardRoot.getElementsByClassName(a.totalLabelDiscount)[0],
H=f["default"].cardRoot.getElementsByClassName(a.totalLabelStandard)[0],(M=L[c])?(v&&(v.style.display="block",T=v.getElementsByClassName(a.discountPercent)[0],U=v.getElementsByClassName(a.discountWhole)[0],V=v.getElementsByClassName(a.discountFractional)[0],W=v.getElementsByClassName(a.discountStrikethrough)[0],T&&(T.innerText=M.discountPercent),U&&(U.innerText=M.bundlePriceWhole),V&&(V.innerText=M.bundlePriceFractional),W&&(ca=p?p[c]:"",W.innerText=ca)),H&&(H.style.display="none")):(v&&(v.style.display=
"none"),H&&(H.style.display="block")));if(y=f["default"].cardRoot.getElementsByClassName(a.buttonSection)[0])C=y.getElementsByClassName("a-button-text")[0],0===x?y.classList.contains("a-button-disabled")||y.classList.add("a-button-disabled"):(y.classList.contains("a-button-disabled")&&y.classList.remove("a-button-disabled"),C&&y.classList.contains("add-to-cart-button")?C.innerText+=": "+l:C&&g&&g.length>=x&&(C.innerText=g[x-1]+": "+l))}return[2]})})},O;(function(a){a.clickHandler="clickHandler";a.checkHandler=
"checkHandler";a.popupHandler="popupHandler";a.discountPopupHandler="discountPopupHandler"})(O||(O={}));var r={simsFbtContainter:"_p13n-desktop-sims-fbt_fbt-desktop_sims-fbt-containter__2Cffh",flexFbtContainer:"_p13n-desktop-sims-fbt_fbt-desktop_flex-fbt-container__3fI_9",fbtCard:"_p13n-desktop-sims-fbt_fbt-desktop_fbt-card__1_smM",shiftUnset:"_p13n-desktop-sims-fbt_fbt-desktop_shift-unset__2gQnZ",detailImageSection:"_p13n-desktop-sims-fbt_fbt-desktop_detail-image-section__1Bw2r",imageBackground:"_p13n-desktop-sims-fbt_fbt-desktop_image-background__DVFnZ",
imageDisplay:"_p13n-desktop-sims-fbt_fbt-desktop_image-display__2oZhY",linkArea:"_p13n-desktop-sims-fbt_fbt-desktop_link-area__1VLAZ",thumbnailBox:"_p13n-desktop-sims-fbt_fbt-desktop_thumbnail-box__4jnIT",newThumbnailBox:"_p13n-desktop-sims-fbt_fbt-desktop_new-thumbnail-box__36bD3",thumbnailBoxSpaced:"_p13n-desktop-sims-fbt_fbt-desktop_thumbnail-box-spaced__3TQmo",thumbnailBoxTight:"_p13n-desktop-sims-fbt_fbt-desktop_thumbnail-box-tight__1EkOu",twoItemThumbnailBox:"_p13n-desktop-sims-fbt_fbt-desktop_two-item-thumbnail-box__jV2am",
twoItemThumbnailBoxSpaced:"_p13n-desktop-sims-fbt_fbt-desktop_two-item-thumbnail-box-spaced__3yLMV",twoItemThumbnailBoxTight:"_p13n-desktop-sims-fbt_fbt-desktop_two-item-thumbnail-box-tight__3VZen",newDetailFaceoutBox:"_p13n-desktop-sims-fbt_fbt-desktop_new-detail-faceout-box___WyNy",faceoutNoPlus:"_p13n-desktop-sims-fbt_fbt-desktop_faceout-no-plus__1Sesx",fbtCheckbox:"_p13n-desktop-sims-fbt_fbt-desktop_fbt-checkbox__GSgEz",titleComponentOverflow3:"_p13n-desktop-sims-fbt_fbt-desktop_title-component-overflow3__26ly1",
titleSection:"_p13n-desktop-sims-fbt_fbt-desktop_title-section__16zUG",displayFlex:"_p13n-desktop-sims-fbt_fbt-desktop_display-flex__1gorZ",priceSection:"_p13n-desktop-sims-fbt_fbt-desktop_price-section__1Wo6p",thumbnailPlus:"_p13n-desktop-sims-fbt_fbt-desktop_thumbnail-plus__zdWox",thumbnailPlusNew:"_p13n-desktop-sims-fbt_fbt-desktop_thumbnail-plus-new__2nZz1",plusPadding:"_p13n-desktop-sims-fbt_fbt-desktop_plus-padding__21zgg",productBox:"_p13n-desktop-sims-fbt_fbt-desktop_product-box__3PBxY",itemDetailsPerAsin:"_p13n-desktop-sims-fbt_fbt-desktop_item-details-per-asin__3DtF1",
itemDeliveryMessagePerAsin:"_p13n-desktop-sims-fbt_fbt-desktop_item-delivery-message-per-asin__WQ7q7",fbtItemCheck:"_p13n-desktop-sims-fbt_fbt-desktop_fbt-item-check__pUIoy",addAllButton:"_p13n-desktop-sims-fbt_fbt-desktop_add-all-button__1TRXG",totalLabel:"_p13n-desktop-sims-fbt_fbt-desktop_total-label__dI983",labelCenter:"_p13n-desktop-sims-fbt_fbt-desktop_label-center__L5TW-",totalPointsLabel:"_p13n-desktop-sims-fbt_fbt-desktop_total-points-label__3r09H",addItems:"_p13n-desktop-sims-fbt_fbt-desktop_add-items__16weX",
chooseItems:"_p13n-desktop-sims-fbt_fbt-desktop_choose-items__15UQx",updatedChooseItems:"_p13n-desktop-sims-fbt_fbt-desktop_updated-choose-items__3BN67",totalAmount:"_p13n-desktop-sims-fbt_fbt-desktop_total-amount__wLVdU",pointsAmount:"_p13n-desktop-sims-fbt_fbt-desktop_points-amount__1SNdT",priceAddToCartBox:"_p13n-desktop-sims-fbt_fbt-desktop_price-add-to-cart-box__3OUdK",pricePointsBox:"_p13n-desktop-sims-fbt_fbt-desktop_price-points-box__1xGfe",shipMessageBox:"_p13n-desktop-sims-fbt_fbt-desktop_ship-message-box__t-OOr",
shippingInfoShowBox:"_p13n-desktop-sims-fbt_fbt-desktop_shipping-info-show-box__17yWM",showDetailsBox:"_p13n-desktop-sims-fbt_fbt-desktop_show-details-box__-R3Xb",showDetails:"_p13n-desktop-sims-fbt_fbt-desktop_show-details__3GnPL",shiftDetails:"_p13n-desktop-sims-fbt_fbt-desktop_shift-details__gffZp",hideDetails:"_p13n-desktop-sims-fbt_fbt-desktop_hide-details__28l17",simsFbtUnselectedItem:"_p13n-desktop-sims-fbt_fbt-desktop_sims-fbt-unselected-item__VQmZx",simsFbtRows:"_p13n-desktop-sims-fbt_fbt-desktop_sims-fbt-rows__2LJXs",
bucketDivider:"_p13n-desktop-sims-fbt_fbt-desktop_bucket-divider__25poP",titleTruncate:"_p13n-desktop-sims-fbt_fbt-desktop_title-truncate__1pPAM",detailRowElement:"_p13n-desktop-sims-fbt_fbt-desktop_detail-row-element__2WDgq",detailRowElementLeftMargin:"_p13n-desktop-sims-fbt_fbt-desktop_detail-row-element-left-margin__UkZ8O",actionDetails:"_p13n-desktop-sims-fbt_fbt-desktop_action-details__18ZiI",actionSection:"_p13n-desktop-sims-fbt_fbt-desktop_action-section__mpQSG",sidePanel:"_p13n-desktop-sims-fbt_fbt-desktop_side-panel__23vsu",
totalLabelDiscount:"_p13n-desktop-sims-fbt_fbt-desktop_total-label-discount__22kv9",totalLabelStandard:"_p13n-desktop-sims-fbt_fbt-desktop_total-label-standard__1E_7d",discountTotal:"_p13n-desktop-sims-fbt_fbt-desktop_discount-total__3gWY9",standardTotal:"_p13n-desktop-sims-fbt_fbt-desktop_standard-total__2a-7Q",discountTotalHeading:"_p13n-desktop-sims-fbt_fbt-desktop_discount-total-heading__ZgTBX",discountPercent:"_p13n-desktop-sims-fbt_fbt-desktop_discount-percent__2eDIi",discountSymbol:"_p13n-desktop-sims-fbt_fbt-desktop_discount-symbol__3pQa1",
discountWhole:"_p13n-desktop-sims-fbt_fbt-desktop_discount-whole__1RPjd",discountDecimal:"_p13n-desktop-sims-fbt_fbt-desktop_discount-decimal__2btcX",discountFractional:"_p13n-desktop-sims-fbt_fbt-desktop_discount-fractional__3qM96",discountStrikethrough:"_p13n-desktop-sims-fbt_fbt-desktop_discount-strikethrough__183L7",discountExperimentHeader:"_p13n-desktop-sims-fbt_fbt-desktop_discount-experiment-header__NotSF",discountTitle:"_p13n-desktop-sims-fbt_fbt-desktop_discount-title__2VmTd",discountTerms:"_p13n-desktop-sims-fbt_fbt-desktop_discount-terms__x_9hA"};
Y._operationNames=[];Y.card=function(){return z.__awaiter(void 0,void 0,void 0,function(){var a,e;return z.__generator(this,function(c){switch(c.label){case 0:return a=Z["default"].setup().define,f["default"].cardRoot?[4,Promise.all([va.setupModal(f["default"].cardRoot.getElementsByClassName("cardRoot")[0])])]:[2];case 1:return c.sent(),fa(r),e=!0,a(O.clickHandler,"click",function(b){if(b.event.target){b=f["default"].cardRoot.getElementsByClassName(r.shippingInfoShowBox);var d=f["default"].cardRoot.getElementsByClassName(r.showDetails)[0],
h=f["default"].cardRoot.getElementsByClassName(r.hideDetails)[0];d&&(e?(d.style.display="none",h.style.display="unset",b&&([].forEach.call(b,function(g,p){g.style.display="block"}),e=!1)):(d.style.display="unset",h.style.display="none",b&&[].forEach.call(b,function(g,p){g.style.display="none"}),e=!0))}}),a(O.checkHandler,"click",function(b){b=b.event.target;if(!b||"fbtCheck"===b.id.substr(0,8)){for(;b&&!b.classList.contains(r.fbtItemCheck)&&!b.classList.contains(r.fbtCheckbox);)b=b.parentElement;
if(b){var d=b.id,h=f["default"].cardRoot.getElementsByClassName("cardRoot")[0],g=void 0;h&&h.dataset.components&&(g=JSON.parse(h.dataset.components));g&&g[d]&&(g[d].checked=!g[d].checked);g&&g[d].checked&&(b.classList.contains(r.simsFbtUnselectedItem)&&b.classList.remove(r.simsFbtUnselectedItem),b.classList.contains(r.fbtCheckDetails)||b.classList.add(r.fbtCheckDetails));g&&!g[d].checked&&(b.classList.remove(r.fbtCheckDetails),b.classList.add(r.simsFbtUnselectedItem));h.dataset.components=JSON.stringify(g);
fa(r)}}}),[2]}})})}});
